#!/bin/sh
if [ -d ~/Solor/test_data ]
then
  osascript -e 'display notification "Initialized data found, skipping data initialization." with title "Komet Installer"'
else
  osascript -e 'display notification "Initializing data..." with title "Komet Installer"'
  mkdir -p ~/Solor/
  sudo -u $USER cp -R /Applications/Komet+data.app/Contents/App/test_data ~/Solor/test_data
#  sudo -u rbradley find /Applications/Komet+data.app/Contents/App/test_data/ -type d >> ~/Downloads/testDirs.txt
#	 sudo -u rbradley find /Applications/Komet+data.app/Contents/App/test_data/ -type f >> ~/Downloads/testFiles.txt
#	 sudo -u rbradley find /Applications/Komet+data.app/Contents/App/test_data/ -type d | sed 's/\/Applications\/Komet+data.app\/Contents\/App//g' | xargs -I@ mkdir -p ~/Solor/@
#	 sudo -u rbradley find /Applications/Komet+data.app/Contents/App/test_data -type f | sed 's/\/Applications\/Komet+data.app\/Contents\/App//g' | xargs -I@ install /Applications/Komet+data.app/Contents/App/@ ~/Solor/@
fi
