#!/bin/sh
if [ -f /Applications/Komet.app/Contents/App/sample_data.zip ]
then
	if [ -d ~/Solor/sample_data ]
	then
	  osascript -e 'display notification "Initialized data found, skipping data initialization." with title "Komet Installer"'
	else
	  osascript -e 'display notification "Initializing data..." with title "Komet Installer"'
	  mkdir -p ~/Solor/
	  sudo -u $USER tar -xf /Applications/Komet.app/Contents/App/sample_data.zip -C ~/Solor/
	fi
fi